"""gallery table

Revision ID: 6a3d2b95b7e9
Revises: 
Create Date: 2019-06-28 21:43:55.660324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3d2b95b7e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('I_file_link', sa.String(length=128), nullable=True),
    sa.Column('II_file_link', sa.String(length=128), nullable=True),
    sa.Column('III_file_link', sa.String(length=128), nullable=True),
    sa.Column('IV_file_link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_III_file_link'), 'gallery', ['III_file_link'], unique=True)
    op.create_index(op.f('ix_gallery_II_file_link'), 'gallery', ['II_file_link'], unique=True)
    op.create_index(op.f('ix_gallery_IV_file_link'), 'gallery', ['IV_file_link'], unique=True)
    op.create_index(op.f('ix_gallery_I_file_link'), 'gallery', ['I_file_link'], unique=True)
    op.create_index(op.f('ix_gallery_product_name'), 'gallery', ['product_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_product_name'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_I_file_link'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_IV_file_link'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_II_file_link'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_III_file_link'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###
